[package]
name = "yak_core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
tokio = { version = "1", features = ["macros" , "rt-multi-thread", "time", "sync"] }
tracing = "0.1"
async-trait = "0.1"
